language: python

python: 3.6

install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt

script:
    - flake8
    - coverage run ./manage.py test

after_success:
    - codecov

notifications:
    email: false
