# Generated by Django 2.2 on 2019-04-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('party', 'thesis', 'stance')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='election',
        ),
    ]
