# Generated by Django 2.2 on 2019-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='short_name',
            field=models.CharField(max_length=127, verbose_name='short name'),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('election', 'full_name'), ('election', 'short_name')},
        ),
    ]
